version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ../../ComplaintService
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/database
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - target: 8080
        published: 8080
        protocol: tcp

volumes:
  postgres_data: {}
